# Generated by Django 5.2 on 2025-04-06 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_diagnosis_diagnosisupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='status',
            new_name='status_update',
        ),
    ]
