# Generated by Django 5.2 on 2025-04-06 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_status_diagnosis_status_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='status_update',
            new_name='status',
        ),
    ]
